name: imperial_assault_dice
description: A package for simulating FFG's Imperial Assault dice behaviour
version: 0.1.0
homepage: https://github.com/arranf/Imperial-Assault-Dice
author: Arran France <arranf@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
  matcher: ^0.12.3